
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class productframe extends javax.swing.JFrame {

    /**
     * Creates new form productframe
     */

    public productframe() {
        initComponents();
        showtable();
        locate();
        thr.start();
                
    }
    
int id=0;

public void locate(){
    addproduct.setLocationRelativeTo(null);
}
final void clearfields(){
     prname.setText("");
     prqty.setValue(1);
     prprc.setText("");
     prprc.setText("");
}
final void setEnableTrue(){
    prname.setEnabled(true);
    ext_quant.setEnabled(true);
    prprc.setEnabled(true);
}
public void showtable(){
     try{
         Class.forName(new connections().driver);
         Connection cnn = DriverManager.getConnection(new connections().local, new connections().ps, new connections().sr);
         Statement st = cnn.createStatement();
         ResultSet rs = st.executeQuery("Select * from products");
         DefaultTableModel md = (DefaultTableModel) tab.getModel();
        md.setRowCount(0);
        while(rs.next()){
          md.addRow(new Object[]{rs.getString("id"),rs.getString("pname"),rs.getString("pquantity"),rs.getString("pprice")});
        }
        
     }catch (ClassNotFoundException ex) { 
        Logger.getLogger(productclass.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(productclass.class.getName()).log(Level.SEVERE, null, ex);
    }
}
public void searchProduct(String pname){
    try{
        Class.forName(new connections().driver);
        Connection con = DriverManager.getConnection(new connections().local,new connections().ps,new connections().sr);
        PreparedStatement prep = con.prepareStatement("Select * from products where id like ? or pname like ?");
        prep.setString(1, "%"+pname+"%");
        prep.setString(2, "%"+pname+"%");
        ResultSet rs = prep.executeQuery();
        DefaultTableModel md = (DefaultTableModel) tab.getModel();
        md.setRowCount(0);
        while(rs.next()){
          md.addRow(new Object[]{rs.getString("id"),rs.getString("pname"),rs.getString("pquantity"),rs.getString("pprice")});
        }
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(productclass.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(productclass.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

public void updateQTY(String key){
     try {
         Class.forName(new connections().driver);
         Connection con = DriverManager.getConnection(new connections().local,new connections().ps,new connections().sr);
         PreparedStatement ps = con.prepareStatement("Select * from products where pname like ?");
         ps.setString(1, "%"+key+"%");
         ResultSet rs = ps.executeQuery();
         DefaultTableModel jtab = (DefaultTableModel) tab.getModel();
         int row = 0;
         while(rs.next()){
             String prodname = rs.getString("pname");
             String qty = rs.getString("pquantity");
             tab.setValueAt(qty, row, 2);
             tab.setValueAt(prodname, row, 1);
             row++;
         }
     }  catch (ClassNotFoundException ex) {
            Logger.getLogger(productframe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(productframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    Thread thr = new Thread(new Runnable() {
    @Override
    public void run() {
        while(true){
        updateQTY(searchtf.getText());
            try {
                
                Thread.sleep(3000);
            } catch (InterruptedException ex) {
                Logger.getLogger(productframe.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
});
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addproduct = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        prname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        prqty = new javax.swing.JSpinner();
        prprc = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addbtn = new javax.swing.JButton();
        canceladd = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        editbtn = new javax.swing.JButton();
        addQbtn = new javax.swing.JButton();
        ext_quant = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        searchtf = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        addproduct.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addproduct.setMinimumSize(new java.awt.Dimension(466, 298));
        addproduct.setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(102, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        prname.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name:");

        prqty.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        prqty.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        prprc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        prprc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        prprc.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantity:");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Price:");

        addbtn.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        canceladd.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        canceladd.setText("Back");
        canceladd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceladdActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Goudy Stout", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("= PRODUCT =");

        editbtn.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        addQbtn.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        addQbtn.setText("Add Q");
        addQbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQbtnActionPerformed(evt);
            }
        });

        ext_quant.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ext_quant.setForeground(new java.awt.Color(255, 255, 0));
        ext_quant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ext_quant.setText("1");
        ext_quant.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addQbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(prname)
                            .addComponent(prprc)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(ext_quant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prqty, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(91, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(canceladd)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(canceladd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prname, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prqty, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ext_quant, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prprc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbtn)
                    .addComponent(editbtn)
                    .addComponent(addQbtn))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout addproductLayout = new javax.swing.GroupLayout(addproduct.getContentPane());
        addproduct.getContentPane().setLayout(addproductLayout);
        addproductLayout.setHorizontalGroup(
            addproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addproductLayout.setVerticalGroup(
            addproductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(560, 388));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUCT", "QAUNTITY", "PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab);

        jButton1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton1.setText("Add Product");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 0));
        jButton4.setText("Log Out");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton5.setText("Delete Product");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton6.setText("Edit Product");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        searchtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtfKeyReleased(evt);
            }
        });

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton7.setText("Add Quantity");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(searchtf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchtf)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
setEnableTrue();
addproduct.setVisible(true);addproduct.setAlwaysOnTop(true);this.setEnabled(false);ext_quant.setText("");
editbtn.setVisible(false);addQbtn.setVisible(false); addbtn.setVisible(true);prqty.setEnabled(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
int d = JOptionPane.showConfirmDialog(addproduct, "Do you want exit the program?","System Confirmation",JOptionPane.YES_NO_OPTION);
if(d==0){
    System.exit(d);
}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        String prodname = prname.getText();
        int prodqty = Integer.parseInt(prqty.getValue().toString());
        Float prodprice = Float.parseFloat(prprc.getValue().toString());
        int a = new productclass().checkprodname(prodname, prodqty, prodprice);
        //

        if(!"".equals(prodname)){
            if(a==0){
                int g = new productclass().addpro(prodname, prodqty, prodprice);
                if(g==1){
                    JOptionPane.showMessageDialog(addproduct, "Product is added", "SYSTEM MESSAGE", JOptionPane.INFORMATION_MESSAGE);
                    showtable();
                    clearfields();
                }
            }else{
                JOptionPane.showMessageDialog(addproduct, "Add to existing product", "SYSTEM MESSAGE", JOptionPane.INFORMATION_MESSAGE);
                showtable();
                clearfields();
            }
        }else{
            JOptionPane.showMessageDialog(addproduct, "Please make sure to fill all fields", "SYSTEM MESSAGE", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void canceladdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceladdActionPerformed
clearfields(); addproduct.setVisible(false);this.setEnabled(true);this.setVisible(true);
    }//GEN-LAST:event_canceladdActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

int tbl = tab.getSelectedRow();
if(tbl==-1){
  JOptionPane.showMessageDialog(rootPane, "Please Select Product", "ERROR MESSAGE", JOptionPane.ERROR_MESSAGE);  
}else{
    String s = tab.getValueAt(tbl, 1).toString();
    int a = JOptionPane.showConfirmDialog(rootPane, "Want to delete "+s+"\nClick  'OK'  to continue","CONFIRMATION",JOptionPane.OK_CANCEL_OPTION);
    if(a==JOptionPane.OK_OPTION){
        int x = JOptionPane.showConfirmDialog(rootPane, "Do you really want to Delete "+s,"CONFIRMATION",JOptionPane.YES_NO_OPTION);
        if(x==JOptionPane.YES_OPTION){
            new productclass().deleteproduct(Integer.parseInt(tab.getValueAt(tbl, 0).toString()));
            showtable();
      } 
    }
}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
setEnableTrue();
int tbl = tab.getSelectedRow();
if(tbl==-1){
  JOptionPane.showMessageDialog(rootPane, "Please Select Product", "ERROR MESSAGE", JOptionPane.ERROR_MESSAGE);  
}else{
    addproduct.setVisible(true);addproduct.setAlwaysOnTop(true);this.setEnabled(false);ext_quant.setText("");
    addbtn.setVisible(false);addQbtn.setVisible(false);editbtn.setVisible(true);prqty.setEnabled(false);
     
      id = Integer.parseInt(tab.getValueAt(tbl, 0).toString());
     String pnm = tab.getValueAt(tbl, 1).toString();
     int pqty = Integer.parseInt(tab.getValueAt(tbl, 2).toString());
     String pprice = tab.getValueAt(tbl, 3).toString();
      prname.setText(pnm);prqty.setValue(pqty); prprc.setText(pprice);
}       
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
if(!prname.getText().equals("")){
int a = new productclass().editProduct(id, prname.getText(), Float.parseFloat(prprc.getValue().toString()));
if(a==1){
   JOptionPane.showMessageDialog(addproduct, "Succesfully Edited", "System Message", JOptionPane.INFORMATION_MESSAGE);  
  clearfields();
  showtable();
   addproduct.setVisible(false);this.setEnabled(true);
}}else{
  JOptionPane.showMessageDialog(addproduct, "Please fill all fields", "ERROR MESSAGE", JOptionPane.ERROR_MESSAGE);  
}
    }//GEN-LAST:event_editbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 this.searchProduct(searchtf.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchtfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtfKeyReleased
this.searchProduct(searchtf.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_searchtfKeyReleased

    private void addQbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQbtnActionPerformed
 
int d = JOptionPane.showConfirmDialog(addproduct, "Do you want to add\n     "+prqty.getValue()+"\n to "+prname.getText()+" ?","System Confirmation",JOptionPane.YES_NO_OPTION);
if(d==JOptionPane.YES_OPTION){
int a = new productclass().addQuantity(id, Integer.parseInt(prqty.getValue().toString()));
if(a==1){
    JOptionPane.showMessageDialog(addproduct, "Succesfully Added to Quantity", "System Message", JOptionPane.INFORMATION_MESSAGE);  
   clearfields();
   showtable();
   addproduct.setVisible(false);this.setEnabled(true);
}else{
   JOptionPane.showMessageDialog(addproduct, "Something went wrong", "ERROR MESSAGE", JOptionPane.ERROR_MESSAGE);  
}}
    }//GEN-LAST:event_addQbtnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
int r = tab.getSelectedRow();
if(r!=-1){
    addproduct.setVisible(true);addproduct.setAlwaysOnTop(true);this.setEnabled(false);
    addbtn.setVisible(false);addQbtn.setVisible(true);editbtn.setVisible(false);
    prname.setEnabled(false);prprc.setEnabled(false);prqty.setEnabled(true);
    id = Integer.parseInt(tab.getValueAt(r, 0).toString());
    Object pnm = tab.getValueAt(r, 1);
    Object quant = tab.getValueAt(r, 2);
    Object prc = tab.getValueAt(r, 3);
    prqty.setValue(1);
    prname.setText(pnm.toString());
    ext_quant.setText(quant.toString());
    prprc.setValue(Float.parseFloat(prc.toString()));
    
}else{
   JOptionPane.showMessageDialog(addproduct, "Please Select Product", "ERROR MESSAGE", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addQbtn;
    private javax.swing.JButton addbtn;
    private javax.swing.JFrame addproduct;
    private javax.swing.JButton canceladd;
    private javax.swing.JButton editbtn;
    private javax.swing.JLabel ext_quant;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField prname;
    private javax.swing.JFormattedTextField prprc;
    private javax.swing.JSpinner prqty;
    private javax.swing.JTextField searchtf;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables

}
